import type { Metadata } from "next";
import { Kulim_Park } from "next/font/google";
import "./globals.css";
import NavbarComp from "@/Components/Navbar/NavbarComp";

const inter = Kulim_Park({ subsets: ["latin"], weight: "600" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarComp />
        {children}
      </body>
    </html>
  );
}
