import type { Metadata } from "next";
import { Kdam_Thmor_Pro } from "next/font/google";
import "./globals.css";
import { NavbarComp } from "@/Components/Navbar/NavbarComp";

const inter = Kdam_Thmor_Pro({ subsets: ["khmer"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarComp />
        {children}
      </body>
    </html>
  );
}
